name: vital_flutter_example
description: Demonstrates how to use the vital_flutter plugin.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  fimber: ^0.6.6
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  disposebag: ^1.5.0
  vital_core: ^1.5.1
  vital_health: ^1.5.1
  vital_devices: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
