name: vital_flutter_example
description: Demonstrates how to use the vital_flutter plugin.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  fimber: ^0.6.6
  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  disposebag: ^1.5.0
  vital_core: ^4.3.3
  vital_health: ^4.3.3
  vital_devices: ^4.3.3
  chopper: ^7.1.1
  url_launcher_ios: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
