name: vital_health_platform_interface
description: The ios platform interface of Vital Health.
version: 1.2.2
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  plugin_platform_interface: ^2.1.0
  vital_core: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
