name: vital_devices_ios
description: The ios implementation of Vital Devices.
version: 4.3.6
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: vital_devices
    platforms:
      ios:
        pluginClass: VitalDevicesPlugin

dependencies:
  flutter:
    sdk: flutter
  vital_core: ^4.3.6
  vital_devices_platform_interface: ^4.3.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fimber: ^0.6.6
