name: vital_core_android
description: The Android implementation of Vital Core.
version: 4.3.4
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: vital_core
    platforms:
      android:
        package: io.vital.core
        pluginClass: VitalCorePlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
