name: vital_devices_platform_interface
description: The platform interface of Vital Devices.
version: 0.0.1
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  rxdart: ^0.27.3
  fimber: ^0.6.6
  plugin_platform_interface: ^2.1.0
  vital_client:
    path: ../../vital_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
