name: vital_health
description: The Vital Health package allowing fitness apps linking with tryvital.io and with support for HealthKit.
version: 3.2.0-beta.2
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      ios:
        default_package: vital_health_ios
      android:
        default_package: vital_health_android

dependencies:
  flutter:
    sdk: flutter
  fimber: ^0.6.6
  json_annotation: ^4.6.0
  vital_core: ^3.2.0-beta.2
  vital_health_platform_interface: ^3.2.0-beta.2
  vital_health_ios: ^3.2.0-beta.2
  vital_health_android: ^3.2.0-beta.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build: ^2.1.1
