name: vital_health_ios
description: The ios implementation of Vital Health.
version: 3.0.1
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: vital_health
    platforms:
      ios:
        dartPluginClass: VitalHealthIos
        pluginClass: VitalHealthPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  fimber: ^0.6.6
  vital_core: ^3.0.1
  vital_health_platform_interface: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
