name: vital_devices
description: The Vital Devices package allowing health devices to connect to the phone.
version: 1.9.0
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      ios:
        default_package: vital_devices_ios
      android:
        default_package: vital_devices_android

dependencies:
  flutter:
    sdk: flutter
  fimber: ^0.6.6
  rxdart: ^0.27.3
  vital_core: ^1.9.0
  vital_devices_platform_interface: ^1.9.0
  vital_devices_android: ^1.9.0
  vital_devices_ios: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
