name: vital_devices
description: The Vital Devices package allowing health devices to connect to the phone.
version: 3.1.4
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      ios:
        default_package: vital_devices_ios
      android:
        default_package: vital_devices_android

dependencies:
  flutter:
    sdk: flutter
  fimber: ^0.6.6
  rxdart: ^0.27.3
  vital_core: ^3.1.4
  vital_devices_platform_interface: ^3.1.4
  vital_devices_android: ^3.1.4
  vital_devices_ios: ^3.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
