name: vital_core_ios
description: The ios implementation of Vital Core.
version: 3.1.0
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: vital_core
    platforms:
      ios:
        pluginClass: VitalCorePlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fimber: ^0.6.6
