name: vital_core
description: The official Flutter package for Vital APIs allowing fitness apps linking with tryvital.io and with support for HealthKit.
version: 4.3.8
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      ios:
        default_package: vital_core_ios
      android:
        default_package: vital_core_android

dependencies:
  flutter:
    sdk: flutter
  chopper: ^7.0.7+1
  http: ^1.1.0
  json_annotation: ^4.8.1
  url_launcher: ^6.2.3
  fimber: ^0.6.6
  vital_core_platform_interface: ^4.3.8
  vital_core_ios: ^4.3.8
  vital_core_android: ^4.3.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build: ^2.1.1
  build_runner: ^2.4.6
  chopper_generator: ^7.0.5+1
  json_serializable: ^6.1.1
