name: vital_core
description: The official Flutter package for Vital APIs allowing fitness apps linking with tryvital.io and with support for HealthKit.
version: 1.5.2
homepage: https://tryvital.io/
repository: https://github.com/tryVital/vital-flutter

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.1
  http: ^0.13.4
  json_annotation: ^4.6.0
  url_launcher: ^6.1.5
  fimber: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build: ^2.1.1
  build_runner: ^2.1.4
  chopper_generator: ^4.0.2
  json_serializable: ^6.1.1
